### ISSUE TITLE
VI Media Manager hangs on startup in 10.15.2

### ISSUE THREAD

**Issue by kinetixnrg** [vidalvanbergen/ViMediaManager#48]
Followed steps to clean out vimedia manager and reinstalled.  Application will not start correctly on Catalina.  hangs on the update tv shows screen.  Just stays at beachball.

[ViMM Crash Report.docx](https://github.com/vidalvanbergen/ViMediaManager/files/4141857/ViMM.Crash.Report.docx)

![2020-01-31_18-27-13](https://user-images.githubusercontent.com/60528093/73581530-84dad980-4457-11ea-8e47-c354a3fa29d8.png)

Thanks.

**Comment by vidalvanbergen** [comment]
If you have a large media collection, you may simply have to keep it running for a while until it's finished loading. This problem may take even longer on networked drives since reading times are usually slower than for local drives.

I had to make some significant changes in order to make ViMM 64bit compatible, which unfortunately causes the progress dialog not to show the progression of loading media. Usually however, it is still doing its best in the background despite looking like it's stuck.

Could you try to simply let it run for a while and see if it eventually loads?

**Comment by kinetixnrg** [comment]
Will do.  Started now and will let run.

BTW> What do you consider a large media collection?

Shawn

**Comment by vidalvanbergen** [comment]
Well, I have about 500 movies and 500 tv shows USB3 connected harddrives which ViMM seems to be able to load within a minute or two each. 

I'd like to think that my collection is fairly large, but then I hear from users who have much more expansive libraries than that, which honestly astonishes me. ;)

**Comment by kinetixnrg** [comment]
Mine is not that big.  It took up to 30 minutes for 54 TV show.  Movies took 18 15 min for 600 movies

Files are on fairly good NAS (Synology DS1618+).

It eventually did come back though but the progress bar window never disappeared and is blank.

Thanks for the support.  It does takes about a minute+ just for the app to start up after the initial scans are done.

Shawn

**Comment by kinetixnrg** [comment]
Yeah it seems to be working but everything I start the app or do an update it takes a LONG time. 10 minutes would not be uncommon.   Is there any kind of lagging I can put on to see why it is taking so long or is it the network drive?  

I did not have this much of an issue in a virtual machine historically with the app. It always seems to take a long time to run native.

Software is great so I am putting the effort to figure thus out. 

Cheers 

Shawn

**Comment by vidalvanbergen** [comment]
I believe it should speed up a little bit if you go to 'Preferences' > 'Extras' and disable the option to 'Show poster images in the media list'.
